import { Company, Contact, User, Dashboard as DashboardType, Tile } from '@/types'

export const mockUser: User = {
  id: 'user-1',
  name: 'John Doe',
  email: 'john.doe@example.com',
  image: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=32&h=32&fit=crop&crop=face',
  company: 'Acme Corp',
  solution: 'AI-powered sales automation platform',
  credits: 100,
  subscription: 'free',
  createdAt: new Date(),
  updatedAt: new Date(),
  // Additional fields for profile settings
  dateOfBirth: '1990-05-15',
}

export const mockCompanies: Company[] = [
  {
    id: 'company-1',
    name: 'TechCorp Solutions',
    url: 'https://techcorp.com',
    description: 'Leading technology solutions provider',
    industry: 'Technology',
    size: '50-200 employees',
    location: 'San Francisco, CA',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
  },
  {
    id: 'company-2',
    name: 'Global Enterprises',
    url: 'https://globalenterprises.com',
    description: 'International manufacturing company',
    industry: 'Manufacturing',
    size: '500+ employees',
    location: 'New York, NY',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
  },
  {
    id: 'company-3',
    name: 'StartupXYZ',
    url: 'https://startupxyz.com',
    description: 'Innovative fintech startup',
    industry: 'Fintech',
    size: '10-50 employees',
    location: 'Austin, TX',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
  },
  {
    id: 'company-4',
    name: 'HealthTech Innovations',
    url: 'https://healthtech.com',
    description: 'Healthcare technology solutions',
    industry: 'Healthcare',
    size: '100-500 employees',
    location: 'Boston, MA',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
  },
  {
    id: 'company-5',
    name: 'EcoGreen Systems',
    url: 'https://ecogreen.com',
    description: 'Environmental technology company',
    industry: 'Environmental',
    size: '50-200 employees',
    location: 'Seattle, WA',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
  },
  {
    id: 'company-6',
    name: 'DataFlow Analytics',
    url: 'https://dataflow.com',
    description: 'Data analytics and business intelligence',
    industry: 'Data Analytics',
    size: '25-100 employees',
    location: 'Chicago, IL',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
  },
  {
    id: 'company-7',
    name: 'RetailMax Corp',
    url: 'https://retailmax.com',
    description: 'Retail technology solutions',
    industry: 'Retail',
    size: '200-1000 employees',
    location: 'Los Angeles, CA',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
  },
  {
    id: 'company-8',
    name: 'CloudScale Technologies',
    url: 'https://cloudscale.com',
    description: 'Cloud computing and infrastructure',
    industry: 'Cloud Computing',
    size: '100-500 employees',
    location: 'Denver, CO',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
  },
  {
    id: 'company-9',
    name: 'FinanceFirst Group',
    url: 'https://financefirst.com',
    description: 'Financial services and consulting',
    industry: 'Financial Services',
    size: '500+ employees',
    location: 'Miami, FL',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
  },
  {
    id: 'company-10',
    name: 'EduTech Solutions',
    url: 'https://edutech.com',
    description: 'Educational technology platform',
    industry: 'Education',
    size: '50-200 employees',
    location: 'Portland, OR',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
  },
  {
    id: 'company-11',
    name: 'AI Dynamics Inc',
    url: 'https://aidynamics.com',
    description: 'Artificial intelligence solutions',
    industry: 'Artificial Intelligence',
    size: '100-500 employees',
    location: 'San Jose, CA',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
  },
  {
    id: 'company-12',
    name: 'Blockchain Ventures',
    url: 'https://blockchainventures.com',
    description: 'Blockchain technology solutions',
    industry: 'Blockchain',
    size: '25-100 employees',
    location: 'San Francisco, CA',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
  },
  {
    id: 'company-13',
    name: 'CyberSec Pro',
    url: 'https://cybersecpro.com',
    description: 'Cybersecurity and data protection',
    industry: 'Cybersecurity',
    size: '50-200 employees',
    location: 'Washington, DC',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
  },
  {
    id: 'company-14',
    name: 'Green Energy Co',
    url: 'https://greenenergy.com',
    description: 'Renewable energy solutions',
    industry: 'Renewable Energy',
    size: '200-1000 employees',
    location: 'Houston, TX',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
  },
  {
    id: 'company-15',
    name: 'Logistics Plus',
    url: 'https://logisticsplus.com',
    description: 'Supply chain and logistics management',
    industry: 'Logistics',
    size: '500+ employees',
    location: 'Memphis, TN',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
  },
  {
    id: 'company-16',
    name: 'MediaStream Corp',
    url: 'https://mediastream.com',
    description: 'Media and entertainment technology',
    industry: 'Media & Entertainment',
    size: '100-500 employees',
    location: 'Los Angeles, CA',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
  },
  {
    id: 'company-17',
    name: 'RealEstate Pro',
    url: 'https://realestatepro.com',
    description: 'Real estate technology platform',
    industry: 'Real Estate',
    size: '50-200 employees',
    location: 'Phoenix, AZ',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
  },
  {
    id: 'company-18',
    name: 'TravelTech Solutions',
    url: 'https://traveltech.com',
    description: 'Travel and tourism technology',
    industry: 'Travel & Tourism',
    size: '25-100 employees',
    location: 'Orlando, FL',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
  },
  {
    id: 'company-19',
    name: 'FoodTech Innovations',
    url: 'https://foodtech.com',
    description: 'Food and beverage technology',
    industry: 'Food & Beverage',
    size: '50-200 employees',
    location: 'Portland, OR',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
  },
  {
    id: 'company-20',
    name: 'SportsTech Arena',
    url: 'https://sportstech.com',
    description: 'Sports technology and analytics',
    industry: 'Sports Technology',
    size: '25-100 employees',
    location: 'Atlanta, GA',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
  },
  {
    id: 'company-21',
    name: 'AutoTech Motors',
    url: 'https://autotech.com',
    description: 'Automotive technology solutions',
    industry: 'Automotive',
    size: '500+ employees',
    location: 'Detroit, MI',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
  },
  {
    id: 'company-22',
    name: 'Fashion Forward',
    url: 'https://fashionforward.com',
    description: 'Fashion and apparel technology',
    industry: 'Fashion & Apparel',
    size: '100-500 employees',
    location: 'New York, NY',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
  },
  
  {
    id: 'company-23',
    name: 'AgriTech Solutions',
    url: 'https://agritech.com',
    description: 'Agricultural technology solutions',
    industry: 'Agriculture',
    size: '50-200 employees',
    location: 'Des Moines, IA',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
  },
  {
    id: 'company-24',
    name: 'SpaceTech Ventures',
    url: 'https://spacetech.com',
    description: 'Aerospace and space technology',
    industry: 'Aerospace',
    size: '100-500 employees',
    location: 'Cape Canaveral, FL',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
  },
  {
    id: 'company-25',
    name: 'MarineTech Corp',
    url: 'https://marinetech.com',
    description: 'Marine and ocean technology',
    industry: 'Marine Technology',
    size: '25-100 employees',
    location: 'Seattle, WA',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
  },
]

export const mockContacts: Contact[] = [
  {
    id: 'contact-1',
    name: 'Sarah Johnson',
    jobTitle: 'VP of Sales',
    email: 'sarah.johnson@techcorp.com',
    linkedinUrl: 'https://linkedin.com/in/sarahjohnson',
    insights: {
      painPoints: ['Scaling sales team productivity', 'Managing multiple enterprise accounts'],
      triggers: ['Revenue growth targets', 'Team performance metrics'],
      responsibilities: ['Sales strategy', 'Team management', 'Client relationships'],
      decisionMakingRole: 'High influence on sales tool selection',
      communicationStyle: 'Direct and results-oriented',
      priorities: ['Revenue growth', 'Team efficiency', 'Client satisfaction']
    },
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
    companyId: 'company-1',
  },
  {
    id: 'contact-2',
    name: 'Michael Chen',
    jobTitle: 'CTO',
    email: 'michael.chen@globalenterprises.com',
    linkedinUrl: 'https://linkedin.com/in/michaelchen',
    insights: {
      painPoints: ['Technical integration challenges', 'Data security concerns'],
      triggers: ['Efficiency improvements', 'Security requirements'],
      responsibilities: ['Technical decisions', 'System integration', 'Security oversight'],
      decisionMakingRole: 'Primary technical decision maker',
      communicationStyle: 'Technical and detail-oriented',
      priorities: ['Efficiency', 'Security', 'Integration']
    },
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
    companyId: 'company-2',
  },
  {
    id: 'contact-3',
    name: 'Emily Rodriguez',
    jobTitle: 'Founder & CEO',
    email: 'emily@startupxyz.com',
    linkedinUrl: 'https://linkedin.com/in/emilyrodriguez',
    insights: {
      painPoints: ['Limited budget', 'Need scalable solutions'],
      triggers: ['Cost-effectiveness', 'Growth potential'],
      responsibilities: ['Strategic decisions', 'Budget management', 'Growth planning'],
      decisionMakingRole: 'Primary decision maker',
      communicationStyle: 'Direct and growth-focused',
      priorities: ['Cost efficiency', 'Scalability', 'Growth']
    },
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
    companyId: 'company-3',
  },
  {
    id: 'contact-4',
    name: 'Tim Cook',
    jobTitle: 'CEO',
    email: 'tim.cook@techcorp.com',
    linkedinUrl: 'https://linkedin.com/in/timcook',
    insights: {
      painPoints: ['Market competition', 'Innovation pressure'],
      triggers: ['Market opportunities', 'Competitive threats'],
      responsibilities: ['Strategic planning', 'Market expansion', 'Innovation'],
      decisionMakingRole: 'Strategic decision maker',
      communicationStyle: 'Visionary and strategic',
      priorities: ['Innovation', 'Market growth', 'Competitive advantage']
    },
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
    companyId: 'company-1',
  },
  {
    id: 'contact-5',
    name: 'Satya Nadella',
    jobTitle: 'CTO',
    email: 'satya.nadella@techcorp.com',
    linkedinUrl: 'https://linkedin.com/in/satyanadella',
    insights: 'Technology visionary with expertise in cloud computing and AI.',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
    companyId: 'company-1',
  },
  {
    id: 'contact-6',
    name: 'John Smith',
    jobTitle: 'VP of Marketing',
    email: 'john.smith@techcorp.com',
    linkedinUrl: 'https://linkedin.com/in/johnsmith',
    insights: 'Marketing strategist focused on brand growth and customer acquisition.',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
    companyId: 'company-1',
  },
  {
    id: 'contact-7',
    name: 'Mark Zuckerberg',
    jobTitle: 'Founder',
    email: 'mark.zuckerberg@techcorp.com',
    linkedinUrl: 'https://linkedin.com/in/markzuckerberg',
    insights: 'Innovation leader with experience in social media and technology platforms.',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
    companyId: 'company-1',
  },
  {
    id: 'contact-8',
    name: 'James Dean',
    jobTitle: 'Head of Engineering',
    email: 'james.dean@techcorp.com',
    linkedinUrl: 'https://linkedin.com/in/jamesdean',
    insights: 'Engineering leader focused on scalable architecture and team development.',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
    companyId: 'company-1',
  },
  {
    id: 'contact-9',
    name: 'Guy Ritchie',
    jobTitle: 'VP of Operations',
    email: 'guy.ritchie@techcorp.com',
    linkedinUrl: 'https://linkedin.com/in/guyritchie',
    insights: 'Operations expert with focus on process optimization and efficiency.',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
    companyId: 'company-1',
  },
  {
    id: 'contact-10',
    name: 'Robert DeNiro',
    jobTitle: 'CFO',
    email: 'robert.deniro@techcorp.com',
    linkedinUrl: 'https://linkedin.com/in/robertdeniro',
    insights: 'Financial strategist with expertise in fundraising and financial planning.',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
    companyId: 'company-1',
  },
  {
    id: 'contact-11',
    name: 'Will Smith',
    jobTitle: 'Head of Sales',
    email: 'will.smith@techcorp.com',
    linkedinUrl: 'https://linkedin.com/in/willsmith',
    insights: 'Sales leader with track record of building high-performing teams.',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
    companyId: 'company-1',
  },
  {
    id: 'contact-12',
    name: 'Jennifer Lopez',
    jobTitle: 'VP of Product',
    email: 'jennifer.lopez@techcorp.com',
    linkedinUrl: 'https://linkedin.com/in/jenniferlopez',
    insights: 'Product strategist focused on user experience and market fit.',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
    companyId: 'company-1',
  },
  {
    id: 'contact-13',
    name: 'Brad Pitt',
    jobTitle: 'Head of Design',
    email: 'brad.pitt@techcorp.com',
    linkedinUrl: 'https://linkedin.com/in/bradpitt',
    insights: 'Design leader with expertise in user interface and brand design.',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
    companyId: 'company-1',
  },
  {
    id: 'contact-14',
    name: 'Angelina Jolie',
    jobTitle: 'VP of HR',
    email: 'angelina.jolie@techcorp.com',
    linkedinUrl: 'https://linkedin.com/in/angelinajolie',
    insights: 'HR leader focused on talent acquisition and company culture.',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
    companyId: 'company-1',
  },
  {
    id: 'contact-15',
    name: 'Tom Cruise',
    jobTitle: 'Head of Security',
    email: 'tom.cruise@techcorp.com',
    linkedinUrl: 'https://linkedin.com/in/tomcruise',
    insights: 'Security expert with focus on cybersecurity and data protection.',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
    companyId: 'company-1',
  },
  {
    id: 'contact-16',
    name: 'Nicole Kidman',
    jobTitle: 'VP of Legal',
    email: 'nicole.kidman@techcorp.com',
    linkedinUrl: 'https://linkedin.com/in/nicolekidman',
    insights: 'Legal expert with expertise in corporate law and compliance.',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
    companyId: 'company-1',
  },
  {
    id: 'contact-17',
    name: 'Leonardo DiCaprio',
    jobTitle: 'Head of Analytics',
    email: 'leonardo.dicaprio@techcorp.com',
    linkedinUrl: 'https://linkedin.com/in/leonardodicaprio',
    insights: 'Data analytics leader with focus on business intelligence and insights.',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
    companyId: 'company-1',
  },
  {
    id: 'contact-18',
    name: 'Kate Winslet',
    jobTitle: 'VP of Customer Success',
    email: 'kate.winslet@techcorp.com',
    linkedinUrl: 'https://linkedin.com/in/katewinslet',
    insights: 'Customer success leader focused on retention and satisfaction.',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
    companyId: 'company-1',
  },
  {
    id: 'contact-19',
    name: 'Matt Damon',
    jobTitle: 'Head of Partnerships',
    email: 'matt.damon@techcorp.com',
    linkedinUrl: 'https://linkedin.com/in/mattdamon',
    insights: 'Partnership strategist with focus on strategic alliances and business development.',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
    companyId: 'company-1',
  },
  {
    id: 'contact-20',
    name: 'Julia Roberts',
    jobTitle: 'VP of Communications',
    email: 'julia.roberts@techcorp.com',
    linkedinUrl: 'https://linkedin.com/in/juliaroberts',
    insights: 'Communications leader with expertise in public relations and brand management.',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
    companyId: 'company-1',
  },
  {
    id: 'contact-21',
    name: 'George Clooney',
    jobTitle: 'Head of Strategy',
    email: 'george.clooney@techcorp.com',
    linkedinUrl: 'https://linkedin.com/in/georgeclooney',
    insights: 'Strategic leader focused on long-term planning and market positioning.',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
    companyId: 'company-1',
  },
  {
    id: 'contact-22',
    name: 'Sandra Bullock',
    jobTitle: 'VP of Innovation',
    email: 'sandra.bullock@techcorp.com',
    linkedinUrl: 'https://linkedin.com/in/sandrabullock',
    insights: 'Innovation leader with focus on emerging technologies and R&D.',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
    companyId: 'company-1',
  },
  {
    id: 'contact-23',
    name: 'Ryan Gosling',
    jobTitle: 'Head of Mobile',
    email: 'ryan.gosling@techcorp.com',
    linkedinUrl: 'https://linkedin.com/in/ryangosling',
    insights: 'Mobile technology expert with focus on app development and user experience.',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
    companyId: 'company-1',
  },
  {
    id: 'contact-24',
    name: 'Emma Stone',
    jobTitle: 'VP of Content',
    email: 'emma.stone@techcorp.com',
    linkedinUrl: 'https://linkedin.com/in/emmastone',
    insights: 'Content strategist with focus on content marketing and storytelling.',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
    companyId: 'company-1',
  },
  {
    id: 'contact-25',
    name: 'Ryan Reynolds',
    jobTitle: 'Head of Growth',
    email: 'ryan.reynolds@techcorp.com',
    linkedinUrl: 'https://linkedin.com/in/ryanreynolds',
    insights: 'Growth hacker with expertise in user acquisition and retention strategies.',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
    companyId: 'company-1',
  },
  {
    id: 'contact-26',
    name: 'Scarlett Johansson',
    jobTitle: 'VP of AI',
    email: 'scarlett.johansson@techcorp.com',
    linkedinUrl: 'https://linkedin.com/in/scarlettjohansson',
    insights: 'AI expert with focus on machine learning and artificial intelligence applications.',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
    companyId: 'company-1',
  },
  {
    id: 'contact-27',
    name: 'Chris Evans',
    jobTitle: 'Head of Infrastructure',
    email: 'chris.evans@techcorp.com',
    linkedinUrl: 'https://linkedin.com/in/chrisevans',
    insights: 'Infrastructure leader with expertise in cloud architecture and DevOps.',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
    companyId: 'company-1',
  },
  {
    id: 'contact-28',
    name: 'Chris Hemsworth',
    jobTitle: 'VP of International',
    email: 'chris.hemsworth@techcorp.com',
    linkedinUrl: 'https://linkedin.com/in/chrishemsworth',
    insights: 'International expansion leader with focus on global market entry.',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
    companyId: 'company-1',
  },
  {
    id: 'contact-29',
    name: 'Tom Hanks',
    jobTitle: 'Head of Quality',
    email: 'tom.hanks@techcorp.com',
    linkedinUrl: 'https://linkedin.com/in/tomhanks',
    insights: 'Quality assurance leader with focus on testing and product excellence.',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
    companyId: 'company-1',
  },
  {
    id: 'contact-30',
    name: 'Meryl Streep',
    jobTitle: 'VP of Training',
    email: 'meryl.streep@techcorp.com',
    linkedinUrl: 'https://linkedin.com/in/merylstreep',
    insights: 'Training and development leader with focus on employee growth and skills.',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
    companyId: 'company-1',
  },
  {
    id: 'contact-31',
    name: 'Denzel Washington',
    jobTitle: 'Head of Diversity',
    email: 'denzel.washington@techcorp.com',
    linkedinUrl: 'https://linkedin.com/in/denzelwashington',
    insights: 'Diversity and inclusion leader with focus on equitable workplace practices.',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
    companyId: 'company-1',
  },
  {
    id: 'contact-32',
    name: 'Oprah Winfrey',
    jobTitle: 'VP of Culture',
    email: 'oprah.winfrey@techcorp.com',
    linkedinUrl: 'https://linkedin.com/in/oprahwinfrey',
    insights: 'Culture leader with focus on company values and employee engagement.',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
    companyId: 'company-1',
  },
  {
    id: 'contact-33',
    name: 'Alex Thompson',
    jobTitle: 'Sales Director',
    email: 'alex.thompson@globalenterprises.com',
    linkedinUrl: 'https://linkedin.com/in/alexthompson',
    insights: {
      painPoints: ['Enterprise sales complexity', 'Partnership management'],
      triggers: ['Revenue targets', 'Partnership opportunities'],
      responsibilities: ['Enterprise sales', 'Partnership development', 'Revenue growth'],
      decisionMakingRole: 'Sales decision maker',
      communicationStyle: 'Relationship-focused',
      priorities: ['Revenue growth', 'Partnerships', 'Enterprise clients']
    },
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
    companyId: 'company-2',
  },
  {
    id: 'contact-34',
    name: 'Maria Garcia',
    jobTitle: 'Marketing Manager',
    email: 'maria.garcia@startupxyz.com',
    linkedinUrl: 'https://linkedin.com/in/mariagarcia',
    insights: {
      painPoints: ['Lead generation challenges', 'Campaign optimization'],
      triggers: ['Marketing performance', 'Lead quality'],
      responsibilities: ['Digital marketing', 'Lead generation', 'Campaign management'],
      decisionMakingRole: 'Marketing decision maker',
      communicationStyle: 'Data-driven and creative',
      priorities: ['Lead generation', 'Campaign ROI', 'Brand awareness']
    },
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
    companyId: 'company-3',
  },
  {
    id: 'contact-35',
    name: 'David Kim',
    jobTitle: 'Product Manager',
    email: 'david.kim@healthtech.com',
    linkedinUrl: 'https://linkedin.com/in/davidkim',
    insights: {
      painPoints: ['User experience challenges', 'Healthcare compliance'],
      triggers: ['User feedback', 'Compliance requirements'],
      responsibilities: ['Product strategy', 'User experience', 'Healthcare tech'],
      decisionMakingRole: 'Product decision maker',
      communicationStyle: 'User-focused and strategic',
      priorities: ['User experience', 'Healthcare compliance', 'Product innovation']
    },
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
    companyId: 'company-4',
  },
  {
    id: 'contact-36',
    name: 'Lisa Wang',
    jobTitle: 'Operations Director',
    email: 'lisa.wang@ecogreen.com',
    linkedinUrl: 'https://linkedin.com/in/lisawang',
    insights: 'Operations expert focused on sustainability and environmental impact.',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
    companyId: 'company-5',
  },
  {
    id: 'contact-37',
    name: 'James Wilson',
    jobTitle: 'Data Scientist',
    email: 'james.wilson@dataflow.com',
    linkedinUrl: 'https://linkedin.com/in/jameswilson',
    insights: 'Data analytics expert with machine learning and AI expertise.',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
    companyId: 'company-6',
  },
  {
    id: 'contact-38',
    name: 'Rachel Brown',
    jobTitle: 'Retail Manager',
    email: 'rachel.brown@retailmax.com',
    linkedinUrl: 'https://linkedin.com/in/rachelbrown',
    insights: 'Retail operations specialist with focus on customer experience and inventory management.',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
    companyId: 'company-7',
  },
  {
    id: 'contact-39',
    name: 'Kevin Lee',
    jobTitle: 'Cloud Architect',
    email: 'kevin.lee@cloudscale.com',
    linkedinUrl: 'https://linkedin.com/in/kevinlee',
    insights: 'Cloud infrastructure expert with focus on scalability and security.',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
    companyId: 'company-8',
  },
  {
    id: 'contact-40',
    name: 'Amanda Davis',
    jobTitle: 'Financial Analyst',
    email: 'amanda.davis@financefirst.com',
    linkedinUrl: 'https://linkedin.com/in/amandadavis',
    insights: 'Financial planning specialist with expertise in investment strategies.',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
    companyId: 'company-9',
  },
  {
    id: 'contact-41',
    name: 'Robert Taylor',
    jobTitle: 'Education Director',
    email: 'robert.taylor@edutech.com',
    linkedinUrl: 'https://linkedin.com/in/roberttaylor',
    insights: 'Educational technology leader focused on learning outcomes and student engagement.',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
    companyId: 'company-10',
  },
  {
    id: 'contact-42',
    name: 'Jennifer Martinez',
    jobTitle: 'AI Research Lead',
    email: 'jennifer.martinez@aidynamics.com',
    linkedinUrl: 'https://linkedin.com/in/jennifermartinez',
    insights: 'AI research specialist with focus on machine learning applications.',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
    companyId: 'company-11',
  },
  {
    id: 'contact-43',
    name: 'Michael Johnson',
    jobTitle: 'Blockchain Developer',
    email: 'michael.johnson@blockchainventures.com',
    linkedinUrl: 'https://linkedin.com/in/michaeljohnson',
    insights: 'Blockchain technology expert with focus on decentralized applications.',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
    companyId: 'company-12',
  },
  {
    id: 'contact-44',
    name: 'Sarah Williams',
    jobTitle: 'Security Engineer',
    email: 'sarah.williams@cybersecpro.com',
    linkedinUrl: 'https://linkedin.com/in/sarahwilliams',
    insights: 'Cybersecurity expert with focus on threat detection and prevention.',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
    companyId: 'company-13',
  },
  {
    id: 'contact-45',
    name: 'Daniel Anderson',
    jobTitle: 'Energy Consultant',
    email: 'daniel.anderson@greenenergy.com',
    linkedinUrl: 'https://linkedin.com/in/danielanderson',
    insights: 'Renewable energy specialist with focus on sustainable solutions.',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
    companyId: 'company-14',
  },
  {
    id: 'contact-46',
    name: 'Jessica Thompson',
    jobTitle: 'Logistics Coordinator',
    email: 'jessica.thompson@logisticsplus.com',
    linkedinUrl: 'https://linkedin.com/in/jessicathompson',
    insights: 'Supply chain expert with focus on optimization and efficiency.',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
    companyId: 'company-15',
  },
  {
    id: 'contact-47',
    name: 'Christopher Garcia',
    jobTitle: 'Media Producer',
    email: 'christopher.garcia@mediastream.com',
    linkedinUrl: 'https://linkedin.com/in/christophergarcia',
    insights: 'Media production specialist with focus on digital content creation.',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
    companyId: 'company-16',
  },
  {
    id: 'contact-48',
    name: 'Ashley Rodriguez',
    jobTitle: 'Real Estate Agent',
    email: 'ashley.rodriguez@realestatepro.com',
    linkedinUrl: 'https://linkedin.com/in/ashleyrodriguez',
    insights: 'Real estate professional with focus on commercial properties and investment.',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
    companyId: 'company-17',
  },
  {
    id: 'contact-49',
    name: 'Matthew Wilson',
    jobTitle: 'Travel Coordinator',
    email: 'matthew.wilson@traveltech.com',
    linkedinUrl: 'https://linkedin.com/in/matthewwilson',
    insights: 'Travel technology specialist with focus on booking systems and customer experience.',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
    companyId: 'company-18',
  },
  {
    id: 'contact-50',
    name: 'Nicole Brown',
    jobTitle: 'Food Scientist',
    email: 'nicole.brown@foodtech.com',
    linkedinUrl: 'https://linkedin.com/in/nicolebrown',
    insights: 'Food technology expert with focus on innovation and sustainability.',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
    companyId: 'company-19',
  },
  {
    id: 'contact-51',
    name: 'Andrew Davis',
    jobTitle: 'Sports Analyst',
    email: 'andrew.davis@sportstech.com',
    linkedinUrl: 'https://linkedin.com/in/andrewdavis',
    insights: 'Sports technology specialist with focus on performance analytics and fan engagement.',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
    companyId: 'company-20',
  },
  {
    id: 'contact-52',
    name: 'Stephanie Miller',
    jobTitle: 'Automotive Engineer',
    email: 'stephanie.miller@autotech.com',
    linkedinUrl: 'https://linkedin.com/in/stephaniemiller',
    insights: 'Automotive technology expert with focus on electric vehicles and autonomous systems.',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
    companyId: 'company-21',
  },
]

export const mockTiles: Tile[] = [
  {
    id: 'tile-1',
    title: 'Company Overview',
    content: null,
    prompt: 'Provide a comprehensive overview of this company, including their business model, key products/services, market position, and recent developments.',
    response: 'TechCorp Solutions is a leading technology company specializing in cloud infrastructure and AI solutions. Founded in 2018, they serve over 500 enterprise clients globally. Their main products include cloud migration tools, AI-powered analytics platforms, and cybersecurity solutions. Recent developments include a $50M Series B funding round and expansion into European markets.',
    position: 0,
    type: 'prompt',
    color: 'white',
    size: 'medium',
    isFlipped: false,
    dashboardId: 'dashboard-1',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
    companyId: 'company-1',
  },
  {
    id: 'tile-2',
    title: 'Competitive Analysis',
    content: null,
    prompt: 'Analyze the competitive landscape for this company. Who are their main competitors, and what are their competitive advantages and disadvantages?',
    response: 'Main competitors include AWS, Microsoft Azure, and Google Cloud. TechCorp\'s advantages: specialized AI integration, competitive pricing, excellent customer support. Disadvantages: smaller market share, limited global presence compared to big tech giants.',
    position: 1,
    type: 'prompt',
    color: 'blue',
    size: 'medium',
    isFlipped: false,
    dashboardId: 'dashboard-1',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
    companyId: 'company-1',
  },
  {
    id: 'tile-3',
    title: 'Funding & Financials',
    content: null,
    prompt: 'Research this company\'s funding history, financial performance, and any recent investment rounds or financial news.',
    response: 'Total funding: $75M across 3 rounds. Series A: $15M (2020), Series B: $50M (2023). Revenue: $25M ARR, growing 150% YoY. Recent news: considering IPO in 2025, expanding R&D team by 40%.',
    position: 2,
    type: 'prompt',
    color: 'green',
    size: 'large',
    isFlipped: false,
    dashboardId: 'dashboard-1',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
    companyId: 'company-1',
  },
  {
    id: 'tile-4',
    title: 'Growth Opportunities',
    content: null,
    prompt: 'Identify potential growth opportunities and expansion plans for this company. What markets or segments could they target?',
    response: 'Key opportunities: 1) Healthcare AI market (growing 25% annually), 2) International expansion (Asia-Pacific region), 3) SMB market penetration, 4) Industry-specific solutions (manufacturing, retail). Recommended focus: healthcare AI given their existing expertise.',
    position: 3,
    type: 'prompt',
    color: 'purple',
    size: 'medium',
    isFlipped: false,
    dashboardId: 'dashboard-1',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
    companyId: 'company-1',
  },
  {
    id: 'tile-5',
    title: 'Challenges & Pain Points',
    content: null,
    prompt: 'What are the main challenges and pain points this company likely faces? How might our solution address these issues?',
    response: 'Main challenges: 1) Talent acquisition in competitive market, 2) Scaling customer support, 3) Data security compliance, 4) Integration complexity with legacy systems. Our solution addresses: automated customer onboarding, built-in compliance features, simplified integration APIs.',
    position: 4,
    type: 'prompt',
    color: 'red',
    size: 'medium',
    isFlipped: false,
    dashboardId: 'dashboard-1',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
    companyId: 'company-1',
  },
  {
    id: 'tile-6',
    title: 'Decision Makers',
    content: null,
    prompt: 'Identify key decision makers and stakeholders at this company. Who would be involved in purchasing decisions?',
    response: 'Key stakeholders: Sarah Johnson (VP Sales), Michael Chen (CTO), David Kim (CFO), Lisa Wang (Head of Operations). Decision process: Technical evaluation (CTO), budget approval (CFO), implementation planning (Operations), final sign-off (VP Sales).',
    position: 5,
    type: 'prompt',
    color: 'yellow',
    size: 'medium',
    isFlipped: false,
    dashboardId: 'dashboard-1',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
    companyId: 'company-1',
  },
]

export const mockDashboard: DashboardType = {
  id: 'dashboard-1',
  name: 'TechCorp Solutions Dashboard',
  template: 'default',
  background: 'gradient',
  backgroundImage: null,
  isPublic: false,
  createdAt: new Date(),
  updatedAt: new Date(),
  userId: 'user-1',
  companyId: 'company-1',
  tiles: mockTiles,
}

export const mockFiles = [
  {
    id: 'file-1',
    name: 'TechCorp_Annual_Report_2023.pdf',
    url: 'data:application/pdf;base64,mock-pdf-data',
    type: 'application/pdf',
    size: 2048576,
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
    companyId: 'company-1',
  },
  {
    id: 'file-2',
    name: 'Competitor_Analysis.xlsx',
    url: 'data:application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;base64,mock-excel-data',
    type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    size: 1024000,
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
    companyId: 'company-1',
  },
  {
    id: 'file-3',
    name: 'Meeting_Notes.txt',
    url: 'data:text/plain;base64,bW9jay10ZXh0LWRhdGE=',
    type: 'text/plain',
    size: 5120,
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
    companyId: 'company-1',
  },
]

export const mockOutreach = [
  {
    id: 'outreach-1',
    type: 'email',
    content: 'Hi Sarah,\n\nI hope this email finds you well. I came across TechCorp Solutions and was impressed by your recent Series B funding and expansion into European markets.\n\nI wanted to reach out because I believe our AI-powered sales automation platform could help TechCorp scale its sales operations more efficiently, especially as you grow internationally.\n\nWould you be open to a brief 15-minute call next week to discuss how we\'ve helped similar technology companies increase their sales productivity by 40%?\n\nBest regards,\nJohn',
    subject: 'Partnership Opportunity - AI Sales Automation for TechCorp',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
    companyId: 'company-1',
    contactId: 'contact-1',
  },
  {
    id: 'outreach-2',
    type: 'call',
    content: 'Opening: "Hi Sarah, this is John from Acme Corp. I hope I\'m not catching you at a bad time."\n\nValue prop: "I wanted to reach out because I saw TechCorp\'s recent funding news and thought our AI sales automation platform might be relevant to your growth plans."\n\nPain point: "Many VP of Sales I work with struggle with scaling their team\'s productivity while maintaining quality."\n\nSolution: "Our platform has helped similar tech companies increase sales productivity by 40% through AI-powered lead scoring and automated follow-ups."\n\nNext steps: "Would you be open to a brief demo next week? I can show you exactly how it works."',
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 'user-1',
    companyId: 'company-1',
    contactId: 'contact-1',
  },
]

// Mock API responses
export const mockApiResponses = {
  companies: mockCompanies,
  contacts: mockContacts,
  dashboard: mockDashboard,
  tiles: mockTiles,
  files: mockFiles,
  outreach: mockOutreach,
}
